name: Flutter Build and Release APK

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get

    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks
    
    - name: Build APK
      env:
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      run: |
        flutter build apk --release --split-per-abi \
          --build-number=${{ github.run_number }} \
          --build-name=0.2.${{ github.run_number }}

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/flutter-apk/*.apk"
        tag: v0.2.${{ github.run_number }}
        name: Release v0.2.${{ github.run_number }}
        body: New release for version 0.2.${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN }}