name: Build Flutter App

on:
  workflow_dispatch:  # Déclenchement manuel du workflow
    inputs:
      build:
        description: 'Trigger build manually'
        required: true
        default: 'true'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'  # Assurez-vous de choisir la version appropriée

      - name: Install dependencies
        run: flutter pub get

      # Compilation Android
      - name: Build Android
        run: flutter build apk --release

      - name: Archive Android APK
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: android-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # Compilation iOS
      - name: Install CocoaPods
        run: |
          brew install cocoapods
          pod setup

      - name: Prepare for iOS build
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp provisioning/App.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          security create-keychain -p "" build.keychain
          security import certs/apple.cer -k build.keychain -T /usr/bin/codesign
          security import certs/apple.p12 -k build.keychain -P "${{ secrets.APPLE_KEY_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain

      - name: Build iOS
        run: flutter build ios --release --no-codesign
